---

# create docker config directoy
- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0700
    owner: root
    group: root

# configure docker deamon json file
- name: configure docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0400
    owner: root
    group: root
  notify: restart docker
