---
- name: Install docker credential helper client
  unarchive:
      src: "{{ docker_ch_source_url }}"
      dest: /usr/local/bin/
      remote_src: yes

# create docker client config directoy
- name: create docker config directory
  file:
    path: /home/{{ item }}/.docker/
    state: directory
    mode: 0700
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ docker_users }}"

# configure docker client json file
- name: configure docker client daemon.json
  template:
    src: config.json.j2
    dest: /home/{{ item }}/.docker/config.json
    mode: 0600
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ docker_users }}"

- name: generate gpg2 batch file
  template:
      src: gpgbatch.j2
      dest: /home/{{ item }}/.docker/gpgbatch
      mode: 0600
      owner: "{{ item }}"
      group: "{{ item }}"
  with_items: "{{ docker_users }}"

- name: generate gpg2 passphrase 
  shell: mkpasswd -l 12 -s 0
  with_items: "{{ docker_users }}"
  register: "{{ item }}pphrase"

- name: generate gpg2 passphrase 
  shell: mkpasswd -l 12 -s 0
  with_items: "{{ docker_users }}"
  register: "{{ item }}pphrase"

- name: generate gpg2 vault to store docker credentials
  shell: gpg2 --gen-key --batch {{ item }}pphrase
  with_items: "{{ docker_users }}"

- name: init pass vault 
  shell: pass init {{ item }}
  with_items: "{{ docker_users }}"


