---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

# TODO: Remove this shim once 18.09.1 or later is released.
- import_tasks: docker-1809-shim.yml
  when: ansible_service_mgr == 'systemd'

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- import_tasks: docker-secure-credentials.yml
  when: docker_secure_config

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: system_users.yml

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users

- include_tasks: config.yml
  tags:
    - "docker_config"

- include_tasks: docker-userns.yml
  when: docker_userns_config

- name: Install Docker Python Module
  apt:
    name: "{{ docker_py_pkg_name | default('python-docker') }}"
    state: "{{ docker_py_pkg_state | default('latest') }}"
  when:
    - docker_install_py_module
  notify: restart docker

- include_tasks: docker-swarm.yml
  tags:
    - "docker_swarm"
